### ISSUE TITLE
NPM version different from current compiled version.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-service-tests#4]
When I clone the repo, do `npm install` and check the lib folder, I get the following at line 94 of `lib/common-tests.js`:

```
people.remove(_ids.Bob).then(function () {
```

When I install version 0.5.4 from npm, it's different.  The `_ids.Bob` argument is missing. I get this for the same line when I open it in the `node_modules` folder:

```
people.remove().then(function () {
```

I just deleted the folder and installed again to make sure I hadn't accidentally modified the file.

**Comment by daffl** [comment]
This can be closed now right?

**Comment by marshallswain** [comment]
Yep thanks.
